app:
  host: 0.0.0.0
  port: 4000
  debug: False

logging:
  level: INFO
  format: '%(asctime)s %(levelname)s: %(message)s in %(filename)s:%(lineno)d'
  location: logs
  filename: homigot.log
  backup_count: 30
  rotate_cycle: midnight
